### ISSUE TITLE
【显存异常增长】关于设置vector_S的param.requires_grad前后的显存奇怪变化现象

### ISSUE THREAD

**Issue by jiaosiyu1999** [zechao-li/SVF-few-shot-segmentation#2]
您好！
我想关于**vector_S的param.requires_grad**向您请教一个问题 [（例如这里）](https://github.com/zechao-li/SVF-few-shot-segmentation/blob/main/model/pfenet.py#L247)

我发现在batchsize为2时，
1. 设置layer2,3,4的param.requires_grad=False时，大约需要**3300M**显存。
2. 若进一步设置vector_S的梯度为True，显存涨到**7200M**。
3. 若设置layer2,34的梯度全为true，显存为**7300M**

也就是说，**解冻vector_S的参数会增加大约4000M显存，而进一步解冻conv_U和conv_V仅增加100M的显存**，我不清楚这一现象的原因，希望能够得到您的解答，谢谢！

**Comment by jiaosiyu1999** [comment]
上述三种设定对应的svf_modules函数分别为：
1. 
![image](https://user-images.githubusercontent.com/114275283/209170658-b3d4dac2-56ee-4cf9-8341-b52671b86c4c.png)

2. 
![image](https://user-images.githubusercontent.com/114275283/209170699-c587b1df-a0f1-4eea-998c-74428f63e646.png)

3. 
![image](https://user-images.githubusercontent.com/114275283/209170786-6ddc78be-63a7-4771-bb02-fc1d14201ea7.png)

**Comment by zechao-li** [comment]
你答复下






      -----------
Zechao Li
     Professor
https://zechao-li.github.io/
     Intelligent Media Analysis Group
     
     
     School of Computer Science and Engineering
     Nanjing University of Science and Technology
 
 
      
 

&nbsp;
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: ***@***.***&gt;;
Date: &nbsp;Thu, Dec 22, 2022 11:35 PM
To: ***@***.***&gt;; 
Cc: ***@***.***&gt;; 
Subject: &nbsp;[zechao-li/SVF-few-shot-segmentation] 【显存异常增长】关于设置vector_S的param.requires_grad前后的显存奇怪变化现象 (Issue #2)

&nbsp;



 
您好！
 我想关于vector_S的param.requires_grad向您请教一个问题 （例如这里）
 
我发现在batchsize为2时，
  
设置layer2,3,4的param.requires_grad=False时，大约需要3300M显存。
 
若进一步设置vector_S的梯度为True，显存涨到7200M。
 
若设置layer2,34的梯度全为true，显存为7300M
  
也就是说，解冻vector_S的参数会增加大约4000M显存，而进一步解冻conv_U和conv_V仅增加100M的显存，我不清楚这一现象的原因，希望能够得到您的解答，谢谢！

**Comment by syp2ysy** [comment]
@jiaosiyu1999 你好，这是很正常的现象。显存的增长的多少主要是由于梯度反传的路径长短决定的。只要将vector_S解冻后，梯度就要传播到layer2中，相比较于freeze backbone肯定会增长很大的显存。这也是后续我们要优化的部分。进一步解冻conv_U和conv_V后梯度同样也是只传播到layer2，因此显存并不会有很大的变化。

**Comment by jiaosiyu1999** [comment]
好的，谢谢解答
